### ISSUE TITLE
Fail running test using only bbduk

### ISSUE THREAD

**Issue by yuxiangtan** [attayeb/snaq#3]
Dear Author,

I tried to use this pipeline. When I test with AB+bb-t16+fp-f17-r21+dd+cls-gg+rrf-d10000.zip, everything ran well.

However, when I test with results/AB/AB+bb-t16+dd+cls-gg+rrf-d10000.zip, it broke at the weighted-unifrac and unweighted-unifrac step.

I tried to repeat the error by running: qiime diversity-lib weighted-unifrac --i-table results/AB/AB+bb-t16+dd_table+rrf-d10000.qza --i-phylogeny results/AB/AB+bb-t16+dd+fasttree_rooted.qza --o-distance-matrix results/AB/AB+bb-t16+dd+rrf-d10000+beta_weightedunifrac.qza
within the corresponding environment, I got the following error:

Plugin error from diversity-lib:

  Invalid shape in axis 0: 0.

Debug info has been saved to /tmp/qiime2-q2cli-err-rx8urlhe.log
double free or corruption (!prev)
Aborted (core dumped)

I am wondering, what's the recommendation of using bbduk and fastq for trimming? In the paper, you said there should be OK to run with any combination?

Best,

Yuxiang Tan

**Comment by attayeb** [comment]
Dear Yuxiang Tan
The reason of this error is that the result matrix was empty. did you check dada table? how many ASVs do you have, probably because of not trimming the primers, all your data did not pass through dada2.

the other possibility is that probably the threshold 10000 is very high, check dada_table file to see how many reads do you have in all your samples and decide the rarefication threshold depending on that.
Best wishes,
Attayeb
    On Sunday, July 17, 2022 at 11:41:31 AM GMT+9, yuxiangtan ***@***.***> wrote:  
 
 


Dear Author,

I tried to use this pipeline. When I test with AB+bb-t16+fp-f17-r21+dd+cls-gg+rrf-d10000.zip, everything ran well.

However, when I test with results/AB/AB+bb-t16+dd+cls-gg+rrf-d10000.zip, it broke at the weighted-unifrac and unweighted-unifrac step.

I tried to repeat the error by running: qiime diversity-lib weighted-unifrac --i-table results/AB/AB+bb-t16+dd_table+rrf-d10000.qza --i-phylogeny results/AB/AB+bb-t16+dd+fasttree_rooted.qza --o-distance-matrix results/AB/AB+bb-t16+dd+rrf-d10000+beta_weightedunifrac.qza
within the corresponding environment, I got the following error:

Plugin error from diversity-lib:

Invalid shape in axis 0: 0.

Debug info has been saved to /tmp/qiime2-q2cli-err-rx8urlhe.log
double free or corruption (!prev)
Aborted (core dumped)

I am wondering, what's the recommendation of using bbduk and fastq for trimming? In the paper, you said there should be OK to run with any combination?

Best,

Yuxiang Tan
